name              'trusted_certificate'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Manages adding certificates to the OS trust store'
version           '3.4.0'
source_url        'https://github.com/sous-chefs/trusted_certificate'
issues_url        'https://github.com/sous-chefs/trusted_certificate/issues'
chef_version      '>= 12.15'

supports 'ubuntu'
supports 'debian'
supports 'redhat'
supports 'centos'
supports 'suse'
supports 'opensuse'
supports 'opensuseleap'
supports 'scientific'
supports 'oracle'
supports 'amazon'
supports 'zlinux'
